version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.6
    container_name: etcd
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data
      --advertise-client-urls http://0.0.0.0:2379
      --listen-client-urls http://0.0.0.0:2379
    ports:
      - "2379:2379"
    networks:
      - spilo-net
    volumes:
      - etcd-data:/etcd-data

  spilo-node1:
    image: registry.opensource.zalan.do/acid/spilo-14:latest
    container_name: spilo-node1
    environment:
      CLUSTER_NAME: spilo-cluster
      SCOPE: spilo-cluster
      APIPORT: 8008
      PGPORT: 5432
      PGUSER_SUPERUSER: postgres
      PGPASSWORD_SUPERUSER: ${POSTGRES_PASSWORD}
      PGUSER_STANDBY: standby
      PGPASSWORD_STANDBY: ${PGPASSWORD_STANDBY}

      # 本地存儲相關配置
      USE_WALG_BACKUP: "true"
      WALG_FILE_PREFIX: "/backups/spilo"
    depends_on:
      - etcd
    ports:
      - "5433:5432"
      - "8009:8008"
    networks:
      - spilo-net
    volumes:
      - spilo-data-node1:/home/postgres/pgdata
      - ./backups:/backups
  spilo-node2:
    image: registry.opensource.zalan.do/acid/spilo-14:latest
    container_name: spilo-node2
    environment:
      CLUSTER_NAME: spilo-cluster
      SCOPE: spilo-cluster
      APIPORT: 8008
      PGPORT: 5432
      PGUSER_SUPERUSER: postgres
      PGPASSWORD_SUPERUSER: ${POSTGRES_PASSWORD}
      PGUSER_STANDBY: standby
      PGPASSWORD_STANDBY: ${PGPASSWORD_STANDBY}

      # 本地存儲相關配置
      USE_WALG_BACKUP: "true"
      WALG_FILE_PREFIX: "/backups/spilo"
    depends_on:
      - etcd
    ports:
      - "5434:5432"
      - "8010:8008"
    networks:
      - spilo-net
    volumes:
      - spilo-data-node2:/home/postgres/pgdata
      - ./backups:/backups
  spilo-node3:
    image: registry.opensource.zalan.do/acid/spilo-14:latest
    container_name: spilo-node3
    environment:
      CLUSTER_NAME: spilo-cluster
      SCOPE: spilo-cluster
      APIPORT: 8008
      PGPORT: 5432
      PGUSER_SUPERUSER: postgres
      PGPASSWORD_SUPERUSER: ${POSTGRES_PASSWORD}
      PGUSER_STANDBY: standby
      PGPASSWORD_STANDBY: ${PGPASSWORD_STANDBY}

      # 本地存儲相關配置
      USE_WALG_BACKUP: "true"
      WALG_FILE_PREFIX: "/backups/spilo"
    depends_on:
      - etcd
    ports:
      - "5435:5432"
      - "8011:8008"
    networks:
      - spilo-net
    volumes:
      - spilo-data-node3:/home/postgres/pgdata
      - ./backups:/backups

  haproxy:
    image: haproxy:2.7
    container_name: haproxy
    depends_on:
      - spilo-node1
      - spilo-node2
      - spilo-node3
    ports:
      - "5000:5000"
    networks:
      - spilo-net
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - spilo-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/entrypoint.sh:/entrypoint-custom.sh:ro
    entrypoint: ["/bin/bash", "/entrypoint-custom.sh"]
    depends_on:
      - haproxy
      - spilo-node1
      - spilo-node2
      - spilo-node3

volumes:
  etcd-data:
  spilo-data-node1:
  spilo-data-node2:
  spilo-data-node3:
  pgadmin-data:

networks:
  spilo-net:
    driver: bridge