scope: postgres-cluster
namespace: /service/
name: patroni-node

restapi:
  listen: 0.0.0.0:8008
  connect_address: patroni:8008

etcd:
  hosts: etcd:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        shared_buffers: 128MB
        synchronous_commit: on
        synchronous_standby_names: 'FIRST 2 (spilo-node2,spilo-node3)'
        wal_level: replica
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
  initdb:
    - encoding: UTF8
    - locale: en_US.UTF-8
  users:
    admin:
      password: password
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: patroni:5432
  data_dir: /var/lib/postgresql/data
  pgpass: /var/lib/postgresql/.pgpass
  authentication:
    replication:
      username: replicator
      password: repl_password
    superuser:
      username: postgres
      password: super_password